#!/usr/bin/env #python
# Input file for PIOL
debug = 0
dt = 0.002
dx = (25, 25, 25)
itio = 50
itstats = 10
mpin = 1
mpout = 1
nn = (113, 113, 1)
np3 = (1, 1, 1)
nt = 1501
tm0 = 0.0
infile = 'in/'
oufile = 'out/'
#**********************************************************
#User customized field (Far-field displacement)
radius = 1e6 #m
rho = 2670. #kg/m^3
vp = 6000. #m/s
vs = 3464. #m/s

#receiver 
t0s = 160. #sec
t0e = 220.
t1s = 0.
t1e = 0.
t2s = 0.
t2e = 0.
t3s = 280.
t3e = 340.
dtheta = 90.
dphi = 360.
# otheta and ophi are optional (must after dtheta and dphi)
otheta = 60
ophi = 160.

comp = 1
endian = 0  # read big-endian data on little-endian machine
usrorig = 2 # 0-> origin is at origin in SORD coordinate
            # 1-> origin on free surface but horizontal coordinate is adjusted to center of fault
            # 2-> origin is average to fault  
nsourceoffset = 1
sourceoffset = (0,0,0,0)
#sourceoffset =  (xoffset,yoffset,zoffset,toffset) # move source but keep receiver fixed  
#**********************************************************

fieldio = [
# define a constant field
#('=', 1, 'const', 1.0, (0.0, 0.0, 0.0), (0.0, 0.0, 0.0), 1, [(1, 41, 1), (1, 41, 1), (1, 2, 1), (0, 0, 1)], '-', 2670.0, ['rho']),
# read or write a file name
('=r', 1, 'const', 1.0, (0.0, 0.0, 0.0), (0.0, 0.0, 0.0), 1,  [(1, 113, 1), (1, 113, 1), (1, 1, 1), (0, 0, 1)], 'faultx', 1.0, ['faultx']),
('=r', 1, 'const', 1.0, (0.0, 0.0, 0.0), (0.0, 0.0, 0.0), 1,  [(1, 113, 1), (1, 113, 1), (1, 1, 1), (0, 0, 1)], 'faulty', 1.0, ['faulty']),
('=r', 1, 'const', 1.0, (0.0, 0.0, 0.0), (0.0, 0.0, 0.0), 1,  [(1, 113, 1), (1, 113, 1), (1, 1, 1), (0, 0, 1)], 'faultz', 1.0, ['faultz']),
('=r', 1, 'const', 1.0, (0.0, 0.0, 0.0), (0.0, 0.0, 0.0), 10, [(1, 113, 1), (1, 113, 1), (1, 1, 1), (1, 1501, 1)], 'mr31', 1.0, ['mr31']),
#('=w', 1, 'const', 1.0, (0.0, 0.0, 0.0), (0.0, 0.0, 0.0), 10, [(1, 161, 1), (1, 1, 1), (1, 2, 1), (1, 801, 1)], 'tinti', 1.0, ['tinti']),
# note:
# 1. static field (it == 0)
#         ii(:,4) = (0,0,1)
#    static field (it == nt)
#         ii(:,4) = (nt,nt,1)
# 2. time-variable (it = from 1,nt)
#         ii(:,4) = (1,nt,1)
]
