#!/usr/bin/env #python
# Input file for PIOL
debug = 0
dt = 0.002
dx = (25, 25, 25)
itio = 50
itstats = 10
mpin = 1
mpout = 1
nn = (301, 301, 1)
np3 = (128, 128, 1)
nt = 10001
tm0 = 0.0
infile = 'in/'
oufile = 'out/'
#**********************************************************
#User customized field (Far-field displacement)
radius = 1e6 #m
rho = 2670. #kg/m^3
vp = 6000. #m/s
vs = 3640. #m/s

#receiver 
t0s = 160. #sec
t0e = 220.
t1s = 0.
t1e = 0.
t2s = 0.
t2e = 0.
t3s = 0.
t3e = 0.
dtheta = 10.
dphi = 10.
# otheta and ophi are optional (must after dtheta and dphi)
#otheta = 10
#ophi = -130.

comp = 0
endian = 0  # read big-endian data on little-endian machine
usrorig = 1 # 0-> origin is at origin in SORD coordinate
            # 1-> origin on free surface but horizontal coordinate is adjusted to center of fault
            # 2-> origin is average to fault  
nsourceoffset = 16
sourceoffset = (0,0,0,0) ( 6416.9162, 1692.4225,0,2.1287) (-4613.3531, 6664.7128,0,2.6000) (-5710.5959,-3359.3634,0,2.1252) (-2457.8540,-1566.8053,0,0.9349) (  936.5570,-2864.6466,0,0.9667) ( 5312.6286, 5287.5914,0,2.4043) ( 5386.4309,-2238.5249,0,1.8710) (-3048.2913,-5063.3949,0,1.8957) (-3689.7436, 2500.9735,0,1.4298) (-8277.1946, 1223.2918,0,2.6838) ( 2324.0171, 4949.6869,0,1.7540) ( 7518.8896,-4100.7937,0,2.7471) ( 1222.6757,-7279.9713,0,2.3678) (-5280.2661,  673.7361,0,1.7074) (-2172.1404, 6615.6714,0,2.2335)
#sourceoffset =  (xoffset,yoffset,zoffset,toffset) # move source but keep receiver fixed  
#**********************************************************

fieldio = [
# define a constant field
#('=', 1, 'const', 1.0, (0.0, 0.0, 0.0), (0.0, 0.0, 0.0), 1, [(1, 41, 1), (1, 41, 1), (1, 2, 1), (0, 0, 1)], '-', 2670.0, ['rho']),
# read or write a file name
('=r', 1, 'const', 1.0, (0.0, 0.0, 0.0), (0.0, 0.0, 0.0), 1, [(1, 301, 1), (1, 301, 1), (1, 1, 1), (0, 0, 1)], 'faultx.resampled', 1.0, ['faultx']),
('=r', 1, 'const', 1.0, (0.0, 0.0, 0.0), (0.0, 0.0, 0.0), 1, [(1, 301, 1), (1, 301, 1), (1, 1, 1), (0, 0, 1)], 'faulty.resampled', 1.0, ['faulty']),
('=r', 1, 'const', 1.0, (0.0, 0.0, 0.0), (0.0, 0.0, 0.0), 1, [(1, 301, 1), (1, 301, 1), (1, 1, 1), (0, 0, 1)], 'faultz.resampled', 1.0, ['faultz']),
('=r', 1, 'const', 1.0, (0.0, 0.0, 0.0), (0.0, 0.0, 0.0), 10, [(1, 301, 1), (1, 301, 1), (1, 1, 1), (1, 10001, 1)], 'mr31.resampled', 1.0, ['mr31']),
#('=w', 1, 'const', 1.0, (0.0, 0.0, 0.0), (0.0, 0.0, 0.0), 10, [(1, 161, 1), (1, 1, 1), (1, 2, 1), (1, 801, 1)], 'tinti', 1.0, ['tinti']),
# note:
# 1. static field (it == 0)
#         ii(:,4) = (0,0,1)
#    static field (it == nt)
#         ii(:,4) = (nt,nt,1)
# 2. time-variable (it = from 1,nt)
#         ii(:,4) = (1,nt,1)
]
